services:
  faster-whisper-server-cuda:
    image: fedirz/faster-whisper-server:latest-cuda
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - hugging_face_cache:/root/.cache/huggingface
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                #device_ids: ['0']
                count: all
                capabilities: [gpu]
#  faster-whisper-server-cpu:
#    image: fedirz/faster-whisper-server:latest-cpu
#    restart: unless-stopped
#    ports:
#      - 8000:8000
#    volumes:
#      - hugging_face_cache:/root/.cache/huggingface
volumes:
  hugging_face_cache:
